### ISSUE TITLE
Chatwork message lottery on reaction icon

### ISSUE THREAD

**Issue by ndthinhsgt** [saigon-tech/chatwork_sgt_bot#27]
## Content
command `\lottery` [message_id]

1. Get chatwork message from message_id
2. Get reaction list and user_id
3. Random reaction and push chatwork for result

**Comment by huynq2007** [comment]
scenario tưởng tượng

sáng vô user nào đó chat với con bot kiểu.
user: "chơi xổ số đê"
bot: "chào mn, mn hãy thả reaction để tham gia xổ số nhé" <-- ghi nhớ message id này

chiều user vô chat chat reply lại cái message hồi sáng
user: "cho xin kết quả sổ xố"
bot: -> random ra kết quả
